#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                       

$on_surface = rgba(dee3e5ff)
$surface_alpha = rgba(0e1416cc)
$tertiary = rgba(bcc5ebff)
$primary = rgba(83d2e3ff)
$surface = rgba(0e1416ff)
