
# --------------------#
#        Theme        #
# --------------------#

# Configure Online status
set -g @online_icon "ok"
set -g @offline_icon "nok"

set -g status-position bottom
set -g status-justify "left"
set -g status-left ""

# left side
set -g  status-right-length 100
set -g  status-right ""
set -ga status-right "#{?client_prefix,#{#[bg=#{@thm_primary_container},fg=#{@thm_primary},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_primary}]  #S }}"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_outline},none]│"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_tertiary}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_outline},none]#{?window_zoomed_flag,│,}"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_secondary}]#{?window_zoomed_flag,  zoom ,}"

# middle
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"

set -g window-status-format "#[fg=#{@thm_fg},bg=#{@thm_surface_bright}] #I #[fg=#{@thm_fg},bg=#{@thm_surface_variant}] #W "
set -g window-status-current-format "#[fg=#000000,bg=#{@thm_primary},bold] #I #[bg=#{@thm_secondary_container},fg=#{@thm_fg},none] #W "

# right
#set -g status-right-length 250
#set -g status-right ""
#set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_primary}] 󰅐 %H:%M "
#set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_outline}, none]│"
#set -ga status-right "#[bg=#{@thm_bg}]#{?#{==:#{online_status},ok},#[fg=#{@thm_rosewater}] 󰖩  ,#[fg=#{@thm_secondary},bold]#[reverse] 󰖪  }"
#set -ga status-right 'Continuum status: #{continuum_status}'
