# vim:fileencoding=utf-8:foldmethod=marker

# Font Configuration
font_size 11.0

# Window Configuration
background_opacity 0.8
background_blur 1

# Cursor Configuration
cursor_shape block
cursor_blink_interval 1

# Scrollback
scrollback_lines 3000

# Terminal features
copy_on_select yes
strip_trailing_spaces smart

# Tab configuration
tab_bar_style powerline
tab_bar_align left

# Shell integration
shell_integration enabled

enable_audio_bell no
confirm_os_window_close 0

map menu send_text all \x1b[24~


allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
