format = """
[╭](bold overlay1)$os$username\
$directory\
$git_branch\
$git_status\
$git_commit\
$time\
\n$character\
$conda\
$python\
"""

# =============Visauls================

palette = 'cyberdream'

[palettes.cyberdream]
text = '{{colors.on_surface.default.hex}}'
overlay1 = '{{colors.surface_container_high.default.hex}}'
color_fg0 = '{{colors.on_surface.default.hex}}'
color_bg0 = '{{colors.surface.default.hex}}'
color_bg1 = '{{colors.surface_container_lowest.default.hex}}'
color_bg3 = '{{colors.surface_container_high.default.hex}}'
color_blue = '{{colors.primary.default.hex}}'
color_aqua = '{{colors.tertiary.default.hex}}'
color_green = '{{colors.secondary.default.hex}}'
color_orange = '{{colors.error_container.default.hex}}'
color_red = '{{colors.error.default.hex}}'
color_yellow = '{{colors.inverse_primary.default.hex}}'
color_pink = '{{colors.secondary_container.default.hex}}'
red = '{{colors.error.default.hex}}'

# =============Modules================

[username]
show_always = true
style_user = "fg:text bold"
style_root = "fg:red bold"
format = '[ $user ]($style)'

[os]
disabled = false
style = "fg:color_pink bold"
format = "([ $symbol ]($style))"

[os.symbols]
Windows = ""
Ubuntu = ""
Debian = ""
Arch = ""
Manjaro = ""
Linux = ""
Macos = ""
Unknown = ""

[directory]
style = "fg:color_blue bold"
format = '( in [ $path ]($style))'
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

[git_branch]
style = "fg:color_yellow"
disabled = false
symbol = ""
format = '( on [$symbol $branch]($style))'

[git_status]
disabled = false
style = "fg:color_orange"
format = ' <([$all_status]($style))>'

[git_commit]
disabled = false
only_detached = false
format = ' [ $hash](fg:color_pink)'
commit_hash_length = 6
tag_disabled = false

[character]
format = """
[╰─$symbol](fg:overlay1) """
success_symbol = '[](fg:text bold)'
error_symbol   = '[](fg:red bold)'

# =======Programs environments========

[python]
disabled = false
symbol = ""
format = '([$symbol $virtualenv](fg:color_yellow)) > '

[conda]
disabled = false
format = '([$symbol $environment](fg:color_green)) > '
