# ▄▄▄ .▐▄• ▄ ▄▄▄ . ▄▄· 
# ▀▄.▀· █▌█▌▪▀▄.▀·▐█ ▌▪
# ▐▀▀▪▄ ·██· ▐▀▀▪▄██ ▄▄
# ▐█▄▄▌▪▐█·█▌▐█▄▄▌▐███▌
#  ▀▀▀ •▀▀ ▀▀ ▀▀▀ ·▀▀▀ 

# Wallpaper
exec-once = setWal
# matugen handles this but adding this kinda make it seamless ig 
exec-once = qs

##

# Polkit
exec-once = /usr/lib/polkit-1/polkit-agent-helper-1
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = hyprsunset
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = nm-applet
exec-once = hypridle

# Optional features: Dock, Vicinae
# exec-once = nwg-dock-hyprland -p left -d -w 5 -nolauncher -ml 5 -l top -hl bottom
# exec-once = vicinae server

# Clipboard
exec-once = wl-paste --type text --watch cliphist -max-items=35 store
exec-once = wl-paste --type image --watch cliphist -max-items=10 store
exec-once = wl-clip-persist --clipboard regular

#exec-once = brightnessctl -s -d asus::kbd_backlight

# Run all startup scripts
exec-once = ~/.local/bin/at_startup
