#!/bin/bash

STARTUP_SCRIPTS="$HOME/.local/bin/startup"

for SCRIPT in $STARTUP_SCRIPTS/*; do
    SCRIPT_NAME="${SCRIPT##*/}"

    if [[ $SCRIPT_NAME == _* ]] || [[ $SCRIPT_NAME =~ \.bak$ ]]; then
        echo "Ignorring $SCRIPT_NAME"
        continue
    fi

    if [[ -f "$SCRIPT" ]] && [[ -x "$SCRIPT" ]]; then 
        "$SCRIPT" > /dev/null 2>&1 &
    fi 
done

