#!/usr/bin/env python3
import subprocess
from time import sleep
from os.path import exists, expanduser

# Preferred device to connect to.
# run `bluetoothctl devices Paired`
# put line with preferred device into this file.
PREFERRED = "~/.config/.toggle-bluetooth.pref"

def run(command: str) -> str:
    proc = subprocess.run(
        command.split(), 
        capture_output=True, text=True, check=True
    )

    return proc.stdout

try:
    out = run("bluetoothctl show")
    is_bluetooth_active = "Powered: yes" in out
    
except subprocess.CalledProcessError:
    is_bluetooth_active = False

if is_bluetooth_active:
    out = run("bluetoothctl devices Connected").strip()

    # Check if there is a connection to a device
    try:
        if out.splitlines()[0].startswith("Device"):
            run("playerctl pause")
    except:
        pass

    run("bluetoothctl power off")
    run("rfkill block bluetooth")

else:
    run("rfkill unblock bluetooth")
    sleep(1)
    run("bluetoothctl power on")
    
    last_device = None
    prefered = expanduser(PREFERRED)

    if exists(prefered):
        f = open(prefered)
        last_device = f.read()
        f.close()
    else:
        out = run("bluetoothctl devices Paired")
        out_lines = out.splitlines()

        if not len(out_lines):
            exit(1)
            
        last_device = out_lines[0]

    device_mac = last_device.split()[1]
    print(device_mac)
    subprocess.run(['bluetoothctl', 'connect', device_mac])
